### ISSUE TITLE
Profile User Info Group (회원의 프로필 정보)

### ISSUE THREAD

**Issue by SeungHyune** [Team-SilverTown/Team-SilverTown-MasilGasil-FE#18]
## Task List
- [x] 회원의 프로필 이미지를 보여준다,
- [x] 회원의 간단한 자기소개를 보여준다.
- [x] 회원의 총 산책 기록을 보여준다.
