### ISSUE TITLE
Log Detail Card 구현(공통 컴포넌트)

### ISSUE THREAD

**Issue by SeungHyune** [Team-SilverTown/Team-SilverTown-MasilGasil-FE#19]
# Log Detail Card 구현

### Task List
- [x] 제목 및 간단한 메모를 보여준다.
- [x] 토글 버튼을 누르면 삭제하기, 수정하기 버튼이 나타난다.
- [x] 하단에는 산책에 관한 정보를 보여준다.(산책 시간, 산책 거리, 운동 칼로리 소모)
