### ISSUE TITLE
Log Simple Card 구현(공통 컴포넌트)

### ISSUE THREAD

**Issue by SeungHyune** [Team-SilverTown/Team-SilverTown-MasilGasil-FE#20]
# Log Simple Card 구현

### Task List
- [x] 산책에 대한 썸네일 이미지를 보여준다.
- [x] 산책한 지역 정보를 보여준다.
- [x] 산책을 한 날짜를 보여준다.(산책하는데 걸린 시간과 거리도 함게 보여준다.)
